id: I12ECCC47
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T11:34:24+00:00'
last_modified: '2022-06-07T18:45:39.615972+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14519
  title: གཙང་གསུམ་རླབས་ཀྱི་ཟེགས་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    1B29:
      image_group_id: I1KG15670
      title: ''
      total_pages: 416
      order: 1
      base_file: 1B29.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
